# config/cable.yml
development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: realtime_search_analytics_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: realtime_search_analytics_production
